# Generated by Django 6.0.3 on 2026-07-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_backend', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='blacklisted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
