# Generated by Django 5.2.6 on 2026-07-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms_backend', '0007_customuser_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pending_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pending_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
