# Generated by Django 6.0.3 on 2026-07-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms_backend', '0008_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp_created_at',
        ),
    ]
