# Generated by Django 6.0.3 on 2026-07-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms_backend', '0009_remove_profile_is_verified_remove_profile_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pending_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pending_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pending_phone_number',
        ),
    ]
