# Generated by Django 6.0.7 on 2026-07-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms_backend', '0010_remove_profile_pending_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
